name: "Using Caching"
on: 
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Whether to execute cache step"
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
    - name: "Setup Node.js"
      uses: actions/setup-node@v4
      with:
        node-version: "22.11.0"
    - name: "Setup pnpm"
      uses: pnpm/action-setup@v4
      with:
        version: "9.12.3"
    - name: "Install dependencies"
      run: pnpm install
    - name: "Testing"
      run: pnpm test
    - name: "Building"
      run: pnpm build
    - name: "Deploy to non-prod"
      run: echo "Deploying to non-prod"