name: "Using Caching"
on: 
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Whether to execute cache step"
        type: boolean
        default: true
      node-version:
        description: "Node.js version"
        type: choice
        options:
          - "18.x"
          - "20.x"
          - "22.x"
        default: "22.x"
jobs:
  install-deps:
    runs-on: ubuntu-latest
    outputs:
      deps-cache-hit: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
    - name: "Setup Node.js"
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: "Setup pnpm"
      uses: pnpm/action-setup@v4
      with:
        version: "9.12.3"
    - name: Calculate cache key
      id: cache-key
      run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT
    - name: "Cache dependencies"
      uses: actions/cache@v3
      if: ${{ inputs.use-cache }}
      id: cache
      with:
        key: ${{ steps.cache-key.outputs.CACHE_KEY }}
        path: 'node_modules'
    - name: "Install dependencies"
      if: steps.cache.outputs.cache-hit != 'true'
      run: pnpm install
  lint-and-test:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
    - name: "Setup Node.js"
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: "Setup pnpm"
      uses: pnpm/action-setup@v4
      with:
        version: "9.12.3"
    - name: "Cache dependencies"
      uses: actions/cache@v3
      if: ${{ inputs.use-cache }}
      id: cache
      with:
        key: ${{ needs.install-deps.outputs.deps-cache-hit }}
        path: 'node_modules'
    - name: "Linting"
      run: echo "Linting""
    - name: "Testing"
      run: echo "Testing"
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
    - name: "Setup Node.js"
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: "Setup pnpm"
      uses: pnpm/action-setup@v4
      with:
        version: "9.12.3"
    - name: "Cache dependencies"
      uses: actions/cache@v3
      if: ${{ inputs.use-cache }}
      id: cache
      with:
        key: ${{ needs.install-deps.outputs.deps-cache-hit }}
        path: 'node_modules'
    - name: "Building"
      run: pnpm build
    - name: "Deploy to non-prod"
      run: echo "Deploying to non-prod"