name: Contexts
on: [push, workflow_dispatch]
env: 
  MY_VAR: "This is a secret"
  MY_OVERWRITTEN_VAR: "This is a overwritten secret from workflow"
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      MY_OVERWRITTEN_VAR: "This is a overwritten secret from job"
    steps:
      - name: Display information about the GitHub context
        run: |
          echo "Eventname is ${{ github.event_name }}"
          echo "Ref is ${{ github.ref }}"
          echo "SHA is ${{ github.sha }}"
          echo "Actor is ${{ github.actor }}"
          echo "ActorID is ${{ github.actor_id }}"
          echo "Worflow is ${{ github.workflow }}"
          echo "RunID is ${{ github.run_id }}"
          echo "Run number is ${{ github.run_number }}"
      - name: Retrieve vars
        env:
          MY_OVERWRITTEN_VAR: "This is a overwritten secret from step"
        run: |
          echo "Variable is ${{ vars.MY_VAR }}"
          echo "Variable is $MY_VAR"
          echo "Overwrriten variable is ${{ env.MY_OVERWRITTEN_VAR }}"