name: Event Filters and Activity Types
on: 
  pull_request:
    # this is an activity type
    types: [opened, synchronize]
    # this is an event filter
    branches: main
jobs: 
  echo: 
    runs-on: ubuntu-latest
    steps: 
      - name: Echo
        run: Running whenever a PR is opened or synchronized AND base branch is main
