name: Second workflow
on:
  # push:
  #   branches:
  #     - dev
  #   paths-ignore:
  #     - 'docs/**'
  # schedule:
  #   - cron: '*/2 * * * *'
  workflow_dispatch:
jobs:
      echo:
        runs-on: ubuntu-latest
        steps:
          - name: Echo
            run: echo ${{ github.event_name }}
