name: Third worflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - name: Install dependencies
        # working-directory: ../../
        run: pnpm install