name: "Working with Artifacts"
on: 
  workflow_dispatch:
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
    - name: "Setup Node.js"
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
    - name: "Setup pnpm"
      uses: pnpm/action-setup@v4
      with:
        version: "9.12.3"
    - name: "Cache dependencies"
      uses: actions/cache@v3
      id: cache
      with:
        key: deps-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
        path: 'node_modules'
    - name: "Install dependencies"
      if: steps.cache.outputs.cache-hit != 'true'
      run: pnpm install
    - name: "Testing"
      run: echo "Testing"
    - name: "Build"
      run: pnpm build
    - name: "Upload build files"
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ./.next
  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./.next